# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BNZCrusaders' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for BNZCrusaders
  
  pod 'Firebase/Core'
  pod 'Fabric', '~> 1.7.13'
  pod 'Crashlytics', '~> 3.10.7'
  
  
 
#  pod 'GoogleMobileVision/FaceDetector'
#  pod 'GoogleMobileVision/MVDataOutput'

pod 'Firebase/Messaging'

end



